# JCP Fall 26 Week 2

---
## Part 1: What is Pandas?
**Pandas** is a definitive Python library used for structured data manipulation and programmatic data analysis. It stores tabular arrays inside two core operational objects:
* **Series**: A 1-Dimensional labeled array holding single-attribute sequences.
* **DataFrame**: A 2-Dimensional labeled grid structured with aligning rows and independent columns.

In [6]:
import os
import pandas as pd
import numpy as np

Create a dataframe manually

In [7]:
manual_data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, None],
    'Salary': [70000, 85000, 95000, 60000]
}
df_manual = pd.DataFrame(manual_data)

display(df_manual)

      Name   Age  Salary
0    Alice  25.0   70000
1      Bob  30.0   85000
2  Charlie  35.0   95000
3    David   NaN   60000

#### 1B: Loading data from CSV

Often, data comes from external files.

In [8]:
df_manual.to_csv('simulated_starbucks_nutrition.csv', index=False)

DATA_PATH = os.path.join(os.getcwd(), 'simulated_starbucks_nutrition.csv')
starbucksdrinks = pd.read_csv(DATA_PATH)

display(starbucksdrinks.head())

      Name   Age  Salary
0    Alice  25.0   70000
1      Bob  30.0   85000
2  Charlie  35.0   95000
3    David   NaN   60000

### Tinker Time: Explore Basic DataFrame Methods

Now that you have your `starbucksdrinks` DataFrame, take a moment to explore some of its fundamental methods. These methods provide quick insights into your data without requiring complex operations.

Run the cell below, and then try changing `starbucksdrinks.head()` to other methods like `starbucksdrinks.tail()`, `starbucksdrinks.sample(5)`, or `starbucksdrinks.columns` to see what they do!

In [10]:
display(starbucksdrinks.tail(2))

      Name   Age  Salary
2  Charlie  35.0   95000
3    David   NaN   60000

### Your Turn: Advanced Manual Data Engineering
Construct a completely custom DataFrame named `df_elections` based on the structural visual from the presentation. Your DataFrame must contain columns for `Candidate`, `Party`, `Percentage`, `Year`, and `Result` containing at least 3 distinct historical records. Display your finalized table.

In [11]:
election_data = {
    "Candidate": ["Eugene McCarthy", "John B. Anderson", "Ross Perot"],
    "Party": ["Independent", "Independent", "Independent"],
    "Percentage": [0.911649, 6.631143, 18.956298],
    "Year": [1976, 1980, 1992],
    "Result": ["loss", "loss", "loss"]
}

df_elections = pd.DataFrame(election_data)

display(df_elections)

          Candidate        Party  Percentage  Year Result
0   Eugene McCarthy  Independent    0.911649  1976   loss
1  John B. Anderson  Independent    6.631143  1980   loss
2        Ross Perot  Independent   18.956298  1992   loss

---
## Part 2: Quick Data Exploration & Diagnostics
Before handling complex programmatic transforms, executing targeted structural scans ensures data alignment:

In [12]:
print("1. df.head() Diagnostic:")
display(starbucksdrinks.head(2))

1. df.head() Diagnostic:

    Name   Age  Salary
0  Alice  25.0   70000
1    Bob  30.0   85000

#### 2B: `df.info()`

`info()` provides a concise summary of a DataFrame, including data types of each column, non-null values, and memory usage. It's crucial for identifying missing data and incorrect data types early on.

In [14]:
print("2. df.info() Column Datatypes & Structural Null Counts:")
starbucksdrinks.info()

2. df.info() Column Datatypes & Structural Null Counts:
<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      str
 1   Age     3 non-null      float64
 2   Salary  4 non-null      int64
dtypes: float64(1), int64(1), str(1)
memory usage: 248.0 bytes

#### 2C: `df.describe()`

For numerical columns, `describe()` generates descriptive statistics such as count, mean, standard deviation, min, max, and quartiles. This helps in understanding the distribution and central tendency of your data.

In [ ]:
print("3. df.describe() Quantitative Metrics Summary:")
display(starbucksdrinks.describe())

3. df.describe() Quantitative Metrics Summary:

        Age        Salary
count   3.0      4.000000
mean   30.0  77500.000000
std     5.0  15545.631755
min    25.0  60000.000000
25%    27.5  67500.000000
50%    30.0  77500.000000
75%    32.5  87500.000000
max    35.0  95000.000000

#### 2D: `df.shape` and `df.size`

`.shape` returns a tuple representing the dimensionality of the DataFrame (rows, columns), while `.size` returns the total number of elements (rows * columns). These are quick checks for the scale of your data.

In [15]:
print(f"4. Dimension Mapping (Rows, Columns): {starbucksdrinks.shape}")
print(f"5. Size Evaluator (Total Cells Matrix): {starbucksdrinks.size}")

4. Dimension Mapping (Rows, Columns): (4, 3)
5. Size Evaluator (Total Cells Matrix): 12

### Tinker Time: Explore Other Diagnostic Methods

The diagnostic methods you just saw (`head()`, `info()`, `describe()`, `shape`, `size`) are just a few of the many ways to quickly understand your DataFrame.

In the cell below, try using other useful methods on `starbucksdrinks` such as `starbucksdrinks.dtypes` (to see column data types), `starbucksdrinks.nunique()` (to count unique values per column), or `starbucksdrinks.isnull().sum()` (to get a count of missing values per column).

In [21]:
starbucksdrinks.nunique()

Name      4
Age       3
Salary    4
dtype: int64

### Your Turn: Diagnose Your `df_elections` DataFrame

Now, apply the diagnostic techniques you just learned to your `df_elections` DataFrame. Use `head()`, `info()`, `describe()`, `shape`, and `size` to get a good understanding of its structure and content.

In [22]:
display(df_elections.head())

df_elections.info()

display(df_elections.describe())

print("Shape:", df_elections.shape)
print("Size:", df_elections.size)

          Candidate        Party  Percentage  Year Result
0   Eugene McCarthy  Independent    0.911649  1976   loss
1  John B. Anderson  Independent    6.631143  1980   loss
2        Ross Perot  Independent   18.956298  1992   loss

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Candidate   3 non-null      str
 1   Party       3 non-null      str
 2   Percentage  3 non-null      float64
 3   Year        3 non-null      int64
 4   Result      3 non-null      str
dtypes: float64(1), int64(1), str(3)
memory usage: 338.0 bytes

       Percentage         Year
count    3.000000     3.000000
mean     8.833030  1982.666667
std      9.221636     8.326664
min      0.911649  1976.000000
25%      3.771396  1978.000000
50%      6.631143  1980.000000
75%     12.793720  1986.000000
max     18.956298  1992.000000

Shape: (3, 5)
Size: 15

---
## Part 3: Selecting, Indexing, and Filtering
* Single brackets `df['Age']` isolate a single structural dimension (**Series**).
* Double brackets `df[['Age']]` encapsulate the selection inside a **DataFrame** format.
* `.loc[]` handles **Label-based** coordinates; `.iloc[]` references strict **Integer-position based** dimensions.
* `.query()` provides readable string logical syntax evaluation.

In [23]:
# 3A: Bracket Selections
series_output = starbucksdrinks['Name']
dataframe_output = starbucksdrinks[['Name', 'Salary']]

print("--- Series Output (single bracket) ---")
display(series_output.head(2))
print("\n--- DataFrame Output (double bracket) ---")
display(dataframe_output.head(2))

--- Series Output (single bracket) ---

0    Alice
1      Bob
Name: Name, dtype: str

--- DataFrame Output (double bracket) ---

    Name  Salary
0  Alice   70000
1    Bob   85000

#### 3B: Deep Index Coordinates via `.loc[]` (Label-based Indexing)

`.loc[]` is used for **label-based** indexing. You provide the row label(s) and column label(s) to select specific data.

In [24]:
print("Value locating via .loc (Row index 2, Label 'Salary'):", starbucksdrinks.loc[2, 'Salary'])

Value locating via .loc (Row index 2, Label 'Salary'): 95000

#### 3C: Deep Index Coordinates via `.iloc[]` (Integer-position based Indexing)

`.iloc[]` is used for **integer-position based** indexing. You provide the row index(es) and column index(es) (starting from 0) to select data.

In [25]:
print("Value locating via .iloc (Row index 2, Column position 2):", starbucksdrinks.iloc[2, 2])

Value locating via .iloc (Row index 2, Column position 2): 95000

#### 3D: `.query()` Expressions

`.query()` provides a readable way to filter DataFrame rows using a string expression. It's often more intuitive for complex conditions than boolean indexing.

In [26]:
filtered_query = starbucksdrinks.query("Salary > 65000")
print("\n--- Output from .query() Statement (Salary > 65000) ---")
display(filtered_query)

--- Output from .query() Statement (Salary > 65000) ---

      Name   Age  Salary
0    Alice  25.0   70000
1      Bob  30.0   85000
2  Charlie  35.0   95000

### Boolean Mask Filters & Arrays
When nesting multi-conditional query filters across vectors, keep conditional elements securely bound inside their own standalone logical brackets:
* `&` indicates **AND** logical intersection logic.
* `|` indicates **OR** logical union logic.

In [27]:
# Multi-conditional Boolean Mapping Array Masking
mask_condition = (starbucksdrinks['Salary'] >= 70000) & (starbucksdrinks['Age'] <= 32)
display(starbucksdrinks[mask_condition])

    Name   Age  Salary
0  Alice  25.0   70000
1    Bob  30.0   85000

#### 3E: Utilizing Inclusive Range Bounds with `.between()`

`.between()` is a convenient method for filtering numerical data within a specified inclusive range.

In [28]:
print("\n--- Filter using .between() Method (Salary between 60000 and 80000) ---")
display(starbucksdrinks[starbucksdrinks['Salary'].between(60000, 80000)])

--- Filter using .between() Method (Salary between 60000 and 80000) ---

    Name   Age  Salary
0  Alice  25.0   70000
3  David   NaN   60000

#### 3F: List Matching with `.isin()`

`.isin()` is useful for filtering rows where a column's values are present in a given list of values.

In [29]:
print("\n--- Filter using .isin() Method (Name is Alice or Charlie) ---")
display(starbucksdrinks[starbucksdrinks['Name'].isin(['Alice', 'Charlie'])])

--- Filter using .isin() Method (Name is Alice or Charlie) ---

      Name   Age  Salary
0    Alice  25.0   70000
2  Charlie  35.0   95000

### Tinker Time: Experiment with Selections and Filters

Now that you've seen how to select and filter data, try experimenting with different combinations on your `starbucksdrinks` DataFrame.

In the cell below, try:
1. Selecting a different set of columns (e.g., `[['Name', 'Age']]`).
2. Creating a new `.query()` condition (e.g., `Age < 30`).
3. Building a new boolean mask (e.g., `(starbucksdrinks['Age'].isna()) | (starbucksdrinks['Salary'] < 70000)`).
4. Using `.between()` or `.isin()` with different values.

In [30]:
# Experiment with selections and filters on `starbucksdrinks` here!
# Example: Select 'Name' and 'Age' columns
display(starbucksdrinks[['Name', 'Age']])

# Try uncommenting and running other examples:
# display(starbucksdrinks.query('Age < 30'))
# display(starbucksdrinks[(starbucksdrinks['Age'].isna())])

      Name   Age
0    Alice  25.0
1      Bob  30.0
2  Charlie  35.0
3    David   NaN

### Your Turn: Filter Your `df_elections` Data

Apply your new selection and filtering skills to your `df_elections` DataFrame.

In the cell below, try to:
1. Select only the `Candidate` and `Percentage` columns.
2. Filter `df_elections` to show only elections where the `Percentage` is greater than 50%.
3. Filter to show records for a specific `Party` (e.g., 'Republican' or 'Democratic').

In [31]:
# Select Candidate and Percentage
display(df_elections[["Candidate", "Percentage"]])

# Elections with Percentage greater than 50%
display(df_elections[df_elections["Percentage"] > 50])

# Elections from the Democratic Party
display(df_elections[df_elections["Party"] == "Democratic"])

          Candidate  Percentage
0   Eugene McCarthy    0.911649
1  John B. Anderson    6.631143
2        Ross Perot   18.956298

Empty DataFrame
Columns: [Candidate, Party, Percentage, Year, Result]
Index: []

Empty DataFrame
Columns: [Candidate, Party, Percentage, Year, Result]
Index: []

---
## Part 4: Sorting & Value Transformation
Learn to scan distinct programmatic occurrences via `.value_counts()` and `.unique()`, and execute computed column definitions using string accessors (`.str`).

In [32]:
# 4A: Unique Frequency Analysis
print("Value Counts for Salary:")
print(starbucksdrinks['Salary'].value_counts())

Value Counts for Salary:
Salary
70000    1
85000    1
95000    1
60000    1
Name: count, dtype: int64

#### 4B: `.unique()` Distinct Value Analysis

`.unique()` returns an array of all the unique values in a Series. It's great for understanding the categories present in a column.

In [33]:
print("Unique Names:", starbucksdrinks['Name'].unique())

Unique Names: <ArrowStringArray>
['Alice', 'Bob', 'Charlie', 'David']
Length: 4, dtype: str

#### 4C: Sorting DataFrames with `.sort_values()`

`.sort_values()` allows you to sort your DataFrame by one or more columns in ascending or descending order.

In [34]:
sorted_df = starbucksdrinks.sort_values(by='Salary', ascending=False)
print("\n--- DataFrame Sorted by Salary (Descending) ---")
display(sorted_df)

--- DataFrame Sorted by Salary (Descending) ---

      Name   Age  Salary
2  Charlie  35.0   95000
1      Bob  30.0   85000
0    Alice  25.0   70000
3    David   NaN   60000

#### 4D: Vector Cleaning & Adding Columns using String Accessors (`.str`)

Pandas provides a `.str` accessor for Series containing string data, allowing you to apply string methods (like `.upper()`, `.lower()`, `.len()`) to every element efficiently. This is often used to create new features or standardize text.

In [35]:
starbucksdrinks['Name_Upper'] = starbucksdrinks['Name'].str.upper()
starbucksdrinks['Name_Lengths'] = starbucksdrinks['Name'].str.len()
print("\n--- Expanded DataFrame with Calculated String Attributes ---")
display(starbucksdrinks)

--- Expanded DataFrame with Calculated String Attributes ---

      Name   Age  Salary Name_Upper  Name_Lengths
0    Alice  25.0   70000      ALICE             5
1      Bob  30.0   85000        BOB             3
2  Charlie  35.0   95000    CHARLIE             7
3    David   NaN   60000      DAVID             5

### Handling Missing Values
Isolate missing blocks programmatically via `.isna()` and clear empty rows using `.dropna()` configurations.

In [36]:
print("Checking for missing fields per column:")
print(starbucksdrinks.isna().sum())

Checking for missing fields per column:
Name            0
Age             1
Salary          0
Name_Upper      0
Name_Lengths    0
dtype: int64

#### 4F: Clearing Empty Rows with `.dropna()`

`.dropna()` is used to remove rows or columns containing missing (NaN) values. You can control how missing values are handled (e.g., `how='any'` to drop if any NaN is present, `how='all'` to drop only if all are NaN).

In [37]:
clean_df = starbucksdrinks.dropna()
print(f"\nShape before cleaning: {starbucksdrinks.shape} | Shape after .dropna(): {clean_df.shape}")
display(clean_df)

Shape before cleaning: (4, 5) | Shape after .dropna(): (3, 5)

      Name   Age  Salary Name_Upper  Name_Lengths
0    Alice  25.0   70000      ALICE             5
1      Bob  30.0   85000        BOB             3
2  Charlie  35.0   95000    CHARLIE             7

### Tinker Time: Experiment with Sorting and String Methods

Practice sorting and using string accessors (`.str`) on the `starbucksdrinks` DataFrame.

In the cell below, try:
1. Sorting `starbucksdrinks` by `Age` in ascending order.
2. Creating a new column that converts the `Name` column to lowercase using `.str.lower()`.
3. Creating a new column that checks if a `Name` starts with a specific letter using `.str.startswith()`.

In [38]:
# 1. Sort by Age in ascending order
display(starbucksdrinks.sort_values("Age"))

# 2. Create a lowercase version of Name
starbucksdrinks["Name_lower"] = starbucksdrinks["Name"].str.lower()

# 3. Check if Name starts with a specific letter
starbucksdrinks["Name_starts_A"] = starbucksdrinks["Name"].str.startswith("A")

display(starbucksdrinks)

      Name   Age  Salary Name_Upper  Name_Lengths
0    Alice  25.0   70000      ALICE             5
1      Bob  30.0   85000        BOB             3
2  Charlie  35.0   95000    CHARLIE             7
3    David   NaN   60000      DAVID             5

      Name   Age  Salary Name_Upper  Name_Lengths Name_lower  Name_starts_A
0    Alice  25.0   70000      ALICE             5      alice           True
1      Bob  30.0   85000        BOB             3        bob          False
2  Charlie  35.0   95000    CHARLIE             7    charlie          False
3    David   NaN   60000      DAVID             5      david          False

### Your Turn: Transform and Sort Your `df_elections` Data

Apply sorting and value transformation techniques to your `df_elections` DataFrame.

In the cell below, try to:
1. Sort `df_elections` by `Year` in descending order.
2. Create a new column called `Winning` that is `True` if `Result` is 'Win' and `False` otherwise.

In [39]:
# 1. Sort by Year in descending order
display(df_elections.sort_values("Year", ascending=False))

# 2. Create a Winning column
df_elections["Winning"] = df_elections["Result"] == "Win"

display(df_elections)

          Candidate        Party  Percentage  Year Result
2        Ross Perot  Independent   18.956298  1992   loss
1  John B. Anderson  Independent    6.631143  1980   loss
0   Eugene McCarthy  Independent    0.911649  1976   loss

          Candidate        Party  Percentage  Year Result  Winning
0   Eugene McCarthy  Independent    0.911649  1976   loss    False
1  John B. Anderson  Independent    6.631143  1980   loss    False
2        Ross Perot  Independent   18.956298  1992   loss    False

---
## Part 5: Aggregation Groupby Routines & Data Merges

In [40]:
left_table = pd.DataFrame({'Emp_ID': [1, 2, 3], 'Role': ['Eng', 'PM', 'Data Sci']})
right_table = pd.DataFrame({'Emp_ID': [2, 3, 4], 'Tenure': [3, 5, 1]})
print("--- Defined Left and Right Tables for Merging ---")
display(left_table)
display(right_table)

--- Defined Left and Right Tables for Merging ---

   Emp_ID      Role
0       1       Eng
1       2        PM
2       3  Data Sci

   Emp_ID  Tenure
0       2       3
1       3       5
2       4       1

In [41]:
# 5A: Advanced Groupby & Explicit Named Dictionary Aggregations
mock_regional_data = pd.DataFrame({
    'State': ['CA', 'CA', 'NY', 'NY', 'CA'],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Count': [295, 239, 150, 110, 340],
    'Year': [2021, 2022, 2021, 2023, 2022]
})

state_summary = mock_regional_data.groupby('State').agg({
    'Count': 'sum',
    'Year': 'max'
})
print("--- Groupby Summary Mapping (.agg) ---")
display(state_summary)

--- Groupby Summary Mapping (.agg) ---

       Count  Year
State
CA       874  2022
NY       260  2023

#### 5B: Groupby Single Column, Multiple Aggregations

Often, you'll want to apply several aggregation functions to a single column within a group. You can do this by passing a list of aggregation functions to `.agg()`.

In [42]:
state_count_stats = mock_regional_data.groupby('State').agg(min_count=('Count', 'min'), max_count=('Count', 'max'), avg_count=('Count', 'mean'))
print("--- Groupby State with Min, Max, and Avg Count ---")
display(state_count_stats)

--- Groupby State with Min, Max, and Avg Count ---

       min_count  max_count   avg_count
State
CA           239        340  291.333333
NY           110        150  130.000000

#### 5C: Groupby Multiple Columns, Single Aggregation

You can also group by multiple columns to create more granular aggregations. Here, we group by both `State` and `Year` to see the total `Count` for each state in each year.

In [43]:
state_year_sum = mock_regional_data.groupby(['State', 'Year']).agg(total_count=('Count', 'sum'))
print("--- Groupby State and Year with Total Count ---")
display(state_year_sum)

--- Groupby State and Year with Total Count ---

            total_count
State Year
CA    2021          295
      2022          579
NY    2021          150
      2023          110

#### 5B: Advanced Filtering over Compiled Groups via Lambdas

After grouping, you can apply further filters to the groups themselves. The `.filter()` method, often used with a `lambda` function, allows you to keep or discard entire groups based on a condition.

In [44]:
filtered_groups = mock_regional_data.groupby('State').filter(lambda x: x['Count'].sum() > 500)
print("\n--- Filtered Groups via Lambda Condition (> 500 total count) ---")
display(filtered_groups)

--- Filtered Groups via Lambda Condition (> 500 total count) ---

  State   Name  Count  Year
0    CA  Alice    295  2021
1    CA    Bob    239  2022
4    CA    Eve    340  2022

#### 5E: Demonstrating Outer Merge

An `outer` merge includes all rows from both DataFrames, filling `NaN` for values that don't have a match in the other DataFrame. It's useful when you want to preserve all information from both sides.

In [45]:
merged_outer = pd.merge(left_table, right_table, on='Emp_ID', how='outer')
print("\n--- Outer Relational Join Merged Data Matrix ---")
display(merged_outer)
print("Difference: Includes all rows from both tables, with NaN for unmatched entries.")

--- Outer Relational Join Merged Data Matrix ---

   Emp_ID      Role  Tenure
0       1       Eng     NaN
1       2        PM     3.0
2       3  Data Sci     5.0
3       4       NaN     1.0

Difference: Includes all rows from both tables, with NaN for unmatched entries.

#### 5F: Demonstrating Left Merge

A `left` merge includes all rows from the *left* DataFrame and matching rows from the *right* DataFrame. If there's no match on the right, it fills with `NaN`. This is useful for adding information to your primary DataFrame without losing any of its original records.

In [46]:
merged_left = pd.merge(left_table, right_table, on='Emp_ID', how='left')
print("\n--- Left Relational Join Merged Data Matrix ---")
display(merged_left)
print("Difference: Keeps all rows from the left table and adds matching data from the right.")

--- Left Relational Join Merged Data Matrix ---

   Emp_ID      Role  Tenure
0       1       Eng     NaN
1       2        PM     3.0
2       3  Data Sci     5.0

Difference: Keeps all rows from the left table and adds matching data from the right.

#### 5G: Demonstrating Right Merge

A `right` merge is the inverse of a left merge: it includes all rows from the *right* DataFrame and matching rows from the *left* DataFrame. Unmatched values from the left are filled with `NaN`.

In [47]:
merged_right = pd.merge(left_table, right_table, on='Emp_ID', how='right')
print("\n--- Right Relational Join Merged Data Matrix ---")
display(merged_right)
print("Difference: Keeps all rows from the right table and adds matching data from the left.")

--- Right Relational Join Merged Data Matrix ---

   Emp_ID      Role  Tenure
0       2        PM       3
1       3  Data Sci       5
2       4       NaN       1

Difference: Keeps all rows from the right table and adds matching data from the left.

#### 5C: Inner vs Outer Relational Joins & Key Discrepancy Scans

`pd.merge()` is essential for combining DataFrames based on common columns (keys). The `how` parameter (e.g., `'inner'`, `'outer'`, `'left'`, `'right'`) dictates how rows are handled when keys don't match across DataFrames.

Here, we demonstrate an `inner` merge, which only keeps rows where the `Emp_ID` exists in both tables.

In [48]:
merged_inner = pd.merge(left_table, right_table, on='Emp_ID', how='inner')
print("\n--- Inner Relational Join Merged Data Matrix ---")
display(merged_inner)

--- Inner Relational Join Merged Data Matrix ---

   Emp_ID      Role  Tenure
0       2        PM       3
1       3  Data Sci       5

### Tinker Time: Experiment with Groupby Aggregations

Practice different `groupby` aggregations on the `mock_regional_data` DataFrame.

In the cell below, try to:
1. Group `mock_regional_data` by `Year` and find the sum of `Count` for each year.
2. Group by `State` and calculate the average `Count`.
3. Use multiple aggregations (e.g., `sum` and `mean`) in a single `groupby` statement.

In [49]:
# 1. Sum of Count by Year
display(mock_regional_data.groupby("Year")["Count"].sum())

# 2. Average Count by State
display(mock_regional_data.groupby("State")["Count"].mean())

# 3. Sum and mean of Count by State
display(mock_regional_data.groupby("State")["Count"].agg(["sum", "mean"]))

Year
2021    445
2022    579
2023    110
Name: Count, dtype: int64

State
CA    291.333333
NY    130.000000
Name: Count, dtype: float64

       sum        mean
State
CA     874  291.333333
NY     260  130.000000

### Your Turn: Groupby and Merge `df_elections` Data

Now, let's challenge your `groupby` and `merge` skills using your `df_elections` DataFrame.

First, create a new DataFrame called `df_candidate_details` with information that could be merged with `df_elections`. For example, it could have `Candidate` and `Approval_Rating` columns.

Then, in the cell below, try to:
1. Group your `df_elections` DataFrame by `Party` and find the average `Percentage` for each party.
2. Perform an `inner merge` between your `df_elections` and `df_candidate_details` DataFrames on the `Candidate` column.

In [59]:
# Create candidate details DataFrame
df_candidate_details = pd.DataFrame({
    "Candidate": ["Eugene McCarthy", "John B. Anderson", "Ross Perot"],
    "Approval_Rating": [45, 52, 48]
})

# 1. Average Percentage by Party
display(df_elections.groupby("Party")["Percentage"].mean())

# 2. Inner merge on Candidate
df_merged = pd.merge(
    df_elections,
    df_candidate_details,
    on="Candidate",
    how="inner"
)

display(df_merged)

Party
Independent    8.83303
Name: Percentage, dtype: float64

,Candidate,Party,Percentage,Year,Result,Winning,Approval_Rating
0,Eugene McCarthy,Independent,0.911649,1976,loss,False,45
1,John B. Anderson,Independent,6.631143,1980,loss,False,52
2,Ross Perot,Independent,18.956298,1992,loss,False,48

---
## Part 6: Streamlit Architecture Concepts
Streamlit engine environments run as independent, continuous background servers via Python and cannot compile inline within notebook code blocks.

To test this system on your machine, copy this code block into a separate file called `app.py` and execute the following terminal command:
```bash
streamlit run app.py
```

In [60]:
streamlit_app_script = """
import streamlit as st
import pandas as pd

# Core Text Framework Configurations
st.title('Live Streamlit Analytics Dashboard')
st.header('Production Data Tracking Portal')
st.write('Dynamic interactive table updates triggered instantaneously upon widget variations:')

df_starbucks = pd.DataFrame({
    'Category': ['Beverage', 'Food', 'Beverage', 'Food'],
    'Calories': [150, 380, 90, 420]
})

# Formulating Interactive User Inputs / Interactive Widget Selection
selected_category = st.selectbox('Select target tracking segment:', df_starbucks['Category'].unique())
filtered_subset = df_starbucks[df_starbucks['Category'] == selected_category]

# Data Display Metrics Layout
st.metric(label='Mean Calorie Yield', value=float(filtered_subset['Calories'].mean()))
st.dataframe(filtered_subset)

# Building Chart Graphics Elements
st.bar_chart(df_starbucks.groupby('Category')['Calories'].mean())
"""
print(streamlit_app_script)

import streamlit as st
import pandas as pd

# Core Text Framework Configurations
st.title('Live Streamlit Analytics Dashboard')
st.header('Production Data Tracking Portal')
st.write('Dynamic interactive table updates triggered instantaneously upon widget variations:')

df_starbucks = pd.DataFrame({
    'Category': ['Beverage', 'Food', 'Beverage', 'Food'],
    'Calories': [150, 380, 90, 420]
})

# Formulating Interactive User Inputs / Interactive Widget Selection
selected_category = st.selectbox('Select target tracking segment:', df_starbucks['Category'].unique())
filtered_subset = df_starbucks[df_starbucks['Category'] == selected_category]

# Data Display Metrics Layout
st.metric(label='Mean Calorie Yield', value=float(filtered_subset['Calories'].mean()))
st.dataframe(filtered_subset)

# Building Chart Graphics Elements
st.bar_chart(df_starbucks.groupby('Category')['Calories'].mean())

---
## Part 7: Regular Expressions (Regex) Text Identification
Regex expressions act as structured filter masks designed to locate complex matching character patterns across text vectors:
* `\d`: Evaluates numeric digit variations (equivalent to `[0-9]`).
* `\w`: Targets alphanumeric string characters (equivalent to `[A-Za-z0-9]`).
* `+`: Greedy quantifier representing one or more continuous character occurrences.

In [61]:
import re

system_log = "Transaction verified by operator 405 on machine index 9821. Critical error log reference code ID: 8812."
numeric_search_pattern = r'\d+'

# 7A: re.findall() Multi-match Scanning
all_matches = re.findall(numeric_search_pattern, system_log)
print("Discovered Numeric Array Match Matches:", all_matches)

Discovered Numeric Array Match Matches: ['405', '9821', '8812']

#### 7B: `re.search()` for First Match

`re.search()` scans through a string looking for the first location where the regular expression produces a match. If a match is found, `re.search()` returns a match object; otherwise, it returns `None`.

In [62]:
search_match = re.search(numeric_search_pattern, system_log)
if search_match:
    print("re.search Execution (first numeric match):", search_match.group())
else:
    print("No match found with re.search.")

re.search Execution (first numeric match): 405

#### 7C: `re.match()` for Start-of-String Match

`re.match()` checks for a match only at the beginning of the string. If the pattern is found at the start, it returns a match object; otherwise, it returns `None`. Note that our `numeric_search_pattern` will not match at the very beginning of `system_log`.

In [63]:
match_result = re.match(numeric_search_pattern, system_log)
if match_result:
    print("re.match Execution (starts at string beginning):", match_result.group())
else:
    print("No match found at the beginning of the string with re.match.")

No match found at the beginning of the string with re.match.

### Tinker Time: Experiment with Regex Patterns

Practice building and testing different regular expression patterns on the `system_log` string.

In the cell below, try to:
1. Extract all sequences of alphanumeric characters using `r'\w+'`.
2. Find the first occurrence of a number followed by a specific word (e.g., 'operator').
3. Extract all four-digit numbers.

In [64]:
# Experiment with different regex patterns on `system_log` here!
# Example: Extract all alphanumeric sequences
import re
alpha_numeric_matches = re.findall(r'\w+', system_log)
print("Alphanumeric Matches:", alpha_numeric_matches)

# Try finding the first number followed by 'operator':
# op_pattern = r'\d+\s+operator'
# operator_match = re.search(op_pattern, system_log)
# if operator_match: print("Operator Match:", operator_match.group())

Alphanumeric Matches: ['Transaction', 'verified', 'by', 'operator', '405', 'on', 'machine', 'index', '9821', 'Critical', 'error', 'log', 'reference', 'code', 'ID', '8812']

### Your Turn: Greedy Quantifier Extraction Challenge
Using the string `course_log_data` provided below, build a custom regular expression pattern using character shorthands to parse and extract only the multi-digit numbers representing year targets (`1976`, `1980`, and `2008`) from the text using `re.findall()`. Print your extracted array outcome.

In [65]:
import re

years = re.findall(r"\b\d{4}\b", course_log_data)

print(years)

NameError: name 'course_log_data' is not defined